### ISSUE TITLE
Crashes on touching "+" button at "yours repositories"

### ISSUE THREAD

**Issue by S--Minecraft** [gitskarios/Gitskarios#275]
When touching `+` Button at the `yours` on `repositories`, it crashes.

P.S. My Android version is 4.4.4

**Comment by alorma** [comment]
I cannot reproduce it.

Which version of the app are you using?

**Comment by S--Minecraft** [comment]
Im using 2.6.8 by SHV31(http://www.au.kddi.com/english/mobile/product/smartphone/shv31/) at Android4.4.4.

**Comment by S--Minecraft** [comment]
The Error says android.view.InflateException: Binary XML file line #20 Error inflating class Button.
Caused by Cant convert color:type=0x2,Not found res/drawable/create_repos_background.xml, res/drawable/create_repos_background_enabled.xml.

**Comment by alorma** [comment]
Hi. Thans for that info, i think i found the error.

please, can you join crashlytics to be able to test latest build, and check if the error is solved?

there is the link: https://betas.to/TVbqhdCA

**Comment by S--Minecraft** [comment]
Ive just installed and tried.
The errors except this issue was solved.
But this issue wasnt solved.

**Comment by alorma** [comment]
Ok thanks

**Comment by S--Minecraft** [comment]
Oh...It wasnt solved.
It was my misunderstanding.
Ill paste the crash report.

```
Build version: 2.8.0 
Build date: 2016-01-16 19:31:08 
Current date: 2016-01-25 15:58:55 
Device: SHARP SHV31 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.CreateRepositoryActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class Button
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2341)
    at android.app.ActivityThread.access$1000(ActivityThread.java:157)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1290)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5232)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class Button
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
    at com.alorma.github.ui.activity.base.BaseActivity.setContentView(BaseActivity.java:54)
    at com.alorma.github.ui.activity.CreateRepositoryActivity.onCreate(CreateRepositoryActivity.java:38)
    at android.app.Activity.performCreate(Activity.java:5239)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2256)
    ... 11 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/create_repos_background.xml from drawable resource ID #0x7f02007e
    at android.content.res.Resources.loadDrawable(Resources.java:2098)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
    at android.view.View.<init>(View.java:3587)
    at android.widget.TextView.<init>(TextView.java:635)
    at android.widget.Button.<init>(Button.java:107)
    at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
    at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:98)
    at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:938)
    at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:992)
    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
    ... 23 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/create_repos_background_enabled.xml from drawable resource ID #0x7f02007f
    at android.content.res.Resources.loadDrawable(Resources.java:2098)
    at android.content.res.Resources.getDrawable(Resources.java:700)
    at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
    at android.content.res.Resources.loadDrawable(Resources.java:2094)
    ... 34 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
    at android.content.res.TypedArray.getColor(TypedArray.java:327)
    at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
    at android.content.res.Resources.loadDrawable(Resources.java:2094)
    ... 39 more
```
