### ISSUE TITLE
Crash when attempting to get file history 

### ISSUE THREAD

**Issue by stgraber** [gitskarios/Gitskarios#331]
When trying to get the history for the templates/lxc-alpine.in in the lxc/lxc repository I'm getting the following crash, consistently. 

Build version: 2.7.9 
Build date: 2016-01-11 21:14:54 
Current date: 2016-01-12 09:53:07 
Device: Sony E5823 

Stack trace:  

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.ContentCommitsActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class LinearBreadcrumb
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
    at android.app.ActivityThread.access$800(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class LinearBreadcrumb
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
    at com.alorma.github.ui.activity.base.BaseActivity.setContentView(BaseActivity.java:43)
    at com.alorma.github.ui.activity.ContentCommitsActivity.onCreate(ContentCommitsActivity.java:41)
    at android.app.Activity.performCreate(Activity.java:6034)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.LinearBreadcrumb" on path: DexPathList[[zip file "/data/app/com.alorma.github-2/base.apk"],nativeLibraryDirectories=[/data/app/com.alorma.github-2/lib/arm, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at android.view.LayoutInflater.createView(LayoutInflater.java:571)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:665)
    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:65)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
    ... 21 more
    Suppressed: java.lang.ClassNotFoundException: android.view.LinearBreadcrumb
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 27 more
    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by jvandenbroek** [comment]
I can confirm this happens with all (at least the ones I tested) files, get the same kind of crash trace.
