### ISSUE TITLE
app crashed 

### ISSUE THREAD

**Issue by SkyzohKey** [gitskarios/Gitskarios#336]
<githubroot>Hey guys. First, thanks for the awesome app you built. I was using it and... It crashed, I dunno why. So I decided to post the backtrace ;)
Here's the backtrace:

`````` log
Build version: 2.8.0 
Build date: 2016-01-16 19:31:08 
Current date: 2016-01-18 16:07:22 
Device: WIKO PULP FAB 4G 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
    at com.alorma.gitskarios.core.client.BaseClient$1.call(BaseClient.java:49)
    at com.alorma.gitskarios.core.client.BaseClient$1.call(BaseClient.java:45)
    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:106)
    at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onError(OperatorZip.java:320)
    at rx.internal.operators.OperatorToObservableList$1.onError(OperatorToObservableList.java:99)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:240)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:616)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:526)
    at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:810)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:240)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:776)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:537)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:526)
    at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:250)
    at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:48)
    at com.alorma.github.sdk.services.client.BaseInfiniteCallback.failure(BaseInfiniteCallback.java:48)
    at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```</githubroot>
``````

**Comment by alorma** [comment]
Thanks, i will check it

**Comment by alorma** [comment]
fixed

**Comment by vicky2102** [comment]
What was the problem?
