### ISSUE TITLE
Crash when writing an issue

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/Gitskarios#351]
```
Build version: 2.8.0 
Build date: 2016-01-16 19:31:08 
Current date: 2016-02-11 10:35:08 
Device: Samsung GT-I9505 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
    at com.alorma.gitskarios.core.client.BaseClient$1.call(BaseClient.java:49)
    at com.alorma.gitskarios.core.client.BaseClient$1.call(BaseClient.java:45)
    at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:106)
    at com.alorma.github.sdk.services.client.BaseInfiniteCallback.failure(BaseInfiniteCallback.java:48)
    at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5951)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by alorma** [comment]
fixed
