### ISSUE TITLE
Can't download release assets in Android 6.0

### ISSUE THREAD

**Issue by Sloy** [gitskarios/Gitskarios#358]
_Issue:_
I tried to download a file from a repo's release, and the app crashed with a Security Exception.

> App version
> 2.8.3
> Git build hash from settings:
> 4337cd4
> Device
> Nexus 6P

_Steps to reproduce:_
- Open https://github.com/scm-spain/tap-da-dev with Gitskarios.
- Navigate to releases.
- Pick _LabLove_
- From the assets tab, select _app-release.apk_

_Crash:_

```
Build version: 2.8.3 
Build date: 2016-02-16 12:18:16 
Current date: 2016-02-19 15:04:08 
Device: Huawei Nexus 6P 

Stack trace:  
java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/gitskarios/app-release.apk: Neither user 10162 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
    at android.os.Parcel.readException(Parcel.java:1620)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
    at android.content.ContentResolver.insert(ContentResolver.java:1231)
    at android.app.DownloadManager.enqueue(DownloadManager.java:946)
    at com.alorma.github.ui.fragment.releases.ReleaseAssetsFragment.downloadFile(ReleaseAssetsFragment.java:87)
    at com.alorma.github.ui.fragment.releases.ReleaseAssetsFragment.onReleaseAssetCLicked(ReleaseAssetsFragment.java:75)
    at com.alorma.github.ui.renderers.releases.assets.ReleaseAssetsRenderer$1.onClick(ReleaseAssetsRenderer.java:38)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by alorma** [comment]
Finally, permissions are here!

**Comment by alorma** [comment]
Fixed @Sloy 

Will be available in the next release

**Comment by Sloy** [comment]
Thanks! That was quick :)
