### ISSUE TITLE
Opening a profile's about URL crashes

### ISSUE THREAD

**Issue by andyleejordan** [gitskarios/Gitskarios#368]
Steps: view events, click user's profile photo on left of event, click user's URL in about section

Expected: Chrome opens user's URL

``````
Build version: 2.8.6 
Build date: 2016-03-07 17:47:56 
Current date: 2016-03-08 00:41:04 
Device: Huawei Nexus 6P 

Stack trace:  
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=neersighted.com }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
    at android.app.Activity.startActivityForResult(Activity.java:3930)
    at android.app.Activity.startActivityForResult(Activity.java:3890)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
    at android.app.Activity.startActivity(Activity.java:4213)
    at android.app.Activity.startActivity(Activity.java:4181)
    at com.alorma.github.bean.ProfileItem$1.onClick(ProfileItem.java:55)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 ```</githubroot></githubroot>
``````

**Comment by alorma** [comment]
Which user?

**Comment by andyleejordan** [comment]
Every user.

**Comment by alorma** [comment]
Not really.

I tested with some users and it doesn't crash.

You mean the last entry in [About] section?

**Comment by andyleejordan** [comment]
Ah, no. Just every user last night by coincidence.

It's only when the site is missing its protocol, like "somesite.com" instead of "http://somesite.com".

**Comment by alorma** [comment]
oh, thanks i get it.

I will fix tonight, thanks

**Comment by andyleejordan** [comment]
Awesome. Thanks!

**Comment by alorma** [comment]
Fixed

**Comment by andyleejordan** [comment]
Yay! Thanks :smile:
