### ISSUE TITLE
App crashing on Login Activity

### ISSUE THREAD

**Issue by mklueh** [gitskarios/Gitskarios#424]
> Git build hash from settings:
> bb5ea8f

_Steps to reproduce:_

Start the App for the first time in widescreen/landscape without beeing logged in.

_Crash (optional):_
Build version: 2.13.1 
Build date: 2016-05-22 09:31:26 
Current date: 2016-05-23 15:26:48 
Device: Sony D5503 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.WelcomeActivity}: java.lang.RuntimeException: Unable to bind views for com.alorma.github.ui.activity.WelcomeActivity
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
    at android.app.ActivityThread.access$800(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.RuntimeException: Unable to bind views for com.alorma.github.ui.activity.WelcomeActivity
    at butterknife.ButterKnife.bind(ButterKnife.java:322)
    at butterknife.ButterKnife.bind(ButterKnife.java:237)
    at com.alorma.github.ui.activity.WelcomeActivity.onCreate(WelcomeActivity.java:39)
    at android.app.Activity.performCreate(Activity.java:5990)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
    ... 10 more
Caused by: java.lang.ClassCastException: android.widget.EditText cannot be cast to android.support.design.widget.TextInputLayout
    at com.alorma.github.ui.activity.WelcomeActivity$$ViewBinder.bind(WelcomeActivity$$ViewBinder.java:14)
    at com.alorma.github.ui.activity.WelcomeActivity$$ViewBinder.bind(WelcomeActivity$$ViewBinder.java:8)
    at butterknife.ButterKnife.bind(ButterKnife.java:319)
    ... 15 more

**Comment by alorma** [comment]
It never hapened to me, but i will check ASAP.

Anyway.... i'm going to redesign the app login, again
