### ISSUE TITLE
Crash at first launch in landscape tablet mode

### ISSUE THREAD

**Issue by fahrradflucht** [gitskarios/Gitskarios#429]
Starting up the app in landscape mode on my Pixel C I got a soft crash.

**Comment by shyim** [comment]
@alorma i could reproduce the error on my tablet too.
Here the Crash Message:

```
05-31 21:09:19.611 8608-8608/com.alorma.github.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.alorma.github.debug, PID: 8608
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github.debug/com.alorma.github.ui.activity.WelcomeActivity}: java.lang.RuntimeException: Unable to bind views for com.alorma.github.ui.activity.WelcomeActivity
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.lang.RuntimeException: Unable to bind views for com.alorma.github.ui.activity.WelcomeActivity
                                                                           at butterknife.ButterKnife.bind(ButterKnife.java:322)
                                                                           at butterknife.ButterKnife.bind(ButterKnife.java:237)
                                                                           at com.alorma.github.ui.activity.WelcomeActivity.onCreate(WelcomeActivity.java:36)
                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                        Caused by: java.lang.IllegalStateException: Required view 'progressBar' with ID 2131755230 for field 'progressBar' was not found. If this view is optional add '@Nullable' annotation.
                                                                           at butterknife.ButterKnife$Finder.findRequiredView(ButterKnife.java:140)
                                                                           at com.alorma.github.ui.activity.WelcomeActivity$$ViewBinder.bind(WelcomeActivity$$ViewBinder.java:17)
                                                                           at com.alorma.github.ui.activity.WelcomeActivity$$ViewBinder.bind(WelcomeActivity$$ViewBinder.java:8)
                                                                           at butterknife.ButterKnife.bind(ButterKnife.java:319)
                                                                           at butterknife.ButterKnife.bind(ButterKnife.java:237) 
                                                                           at com.alorma.github.ui.activity.WelcomeActivity.onCreate(WelcomeActivity.java:36) 
                                                                           at android.app.Activity.performCreate(Activity.java:6251) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by alorma** [comment]
Thanks!

I will check for the next release
