### ISSUE TITLE
Signed commits

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#431]
Please mark signed commits in app. ty

**Comment by alorma** [comment]
Trying...

**Comment by alorma** [comment]
I tested it, and seems api have some bugs with it. I will be aware of that.

Thanks

**Comment by alorma** [comment]
Hi @paulkramme!

I will add it first on commit detail screen, waiting for api works :)

**Comment by pkramme** [comment]
Thank you very much :) Great support!

**Comment by alorma** [comment]
Yay! Good news!

Github team updated the API, and now i can get the commits list with verification :)

**Comment by pkramme** [comment]
Great!

**Comment by alorma** [comment]
Uploading ...

**Comment by shyim** [comment]
Sometimes when a commit is signed the app is crashing

Build version: 2.14.4 
Build date: 2016-06-03 16:27:44 
Current date: 2016-06-04 00:02:59 
Device: Asus Nexus 7 

Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'com.alorma.github.sdk.bean.dto.response.GitCommitVerification com.alorma.github.sdk.bean.dto.response.GitCommit.verification' on a null object reference
    at com.alorma.github.ui.fragment.events.EventsListFragment$CommitsAdapter.isCommitVerified(EventsListFragment.java:506)
    at com.alorma.github.ui.fragment.events.EventsListFragment$CommitsAdapter.bindVerification(EventsListFragment.java:501)
    at com.alorma.github.ui.fragment.events.EventsListFragment$CommitsAdapter.getView(EventsListFragment.java:493)
    at android.widget.AbsListView.obtainView(AbsListView.java:2348)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)
    at android.widget.ListView.onMeasure(ListView.java:1188)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
    at android.view.View.measure(View.java:18797)
    at com.afollestad.materialdialogs.internal.MDRootLayout.onMeasure(MDRootLayout.java:199)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2658)
    at android.view.View.measure(View.java:18797)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1199)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by alorma** [comment]
Will check! Thanks

**Comment by alorma** [comment]
Done
