### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by LER0ever** [gitskarios/Gitskarios#447]
_Issue:_
Crashes on first start

Here is my Log. I am not good at Android dev, so i cannot make any solution after skimming the log

Build version: 2.13.2 
Build date: 2016-05-24 20:14:46 
Current date: 2016-06-04 22:59:38 
Device: OnePlus A2001 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2360)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
    at android.app.ActivityThread.access$800(ActivityThread.java:153)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1334)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:139)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:927)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:722)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
    at com.google.android.gms.flags.impl.FlagProviderImpl.getBooleanFlagValue(Unknown Source)
    at com.google.android.gms.internal.zzsd$zza.zzb(Unknown Source)
    at com.google.android.gms.internal.zzsd$zza.zza(Unknown Source)
    at com.google.android.gms.internal.zzsf.zzb(Unknown Source)
    at com.google.android.gms.internal.zzsd.get(Unknown Source)
    at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
    at com.google.firebase.crash.FirebaseCrash.zzOW(Unknown Source)
    at com.google.firebase.crash.FirebaseCrash.report(Unknown Source)
    at com.alorma.github.ui.activity.MainActivity.onCreate(MainActivity.java:96)
    at android.app.Activity.performCreate(Activity.java:6066)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2313)
    ... 10 more

**Comment by alorma** [comment]
Try updating to the lateste version 2.13.6, plz :)

**Comment by LER0ever** [comment]
thank you, i didn't notice the update and it's working fine(2.13.6)
