### ISSUE TITLE
Since update I cannot open my repositories - please help. thanks!

### ISSUE THREAD

**Issue by mattsage** [gitskarios/Gitskarios#450]
Build version: 2.14.9 
Build date: 2016-06-07 19:22:26 
Current date: 2016-06-08 11:33:44 
Device: LGE Nexus 5

**Comment by alorma** [comment]
Hi.

Does it apply?

**Comment by mattsage** [comment]
Yes it does but i was worried about personal details in the output log. 

The App crashed with a picture of a ladybird every time i open up my "repositories "

**Comment by alorma** [comment]
mmmmm ok, that's not cool.

Can you send me the log via mail? gitskarios@gmail.com, i will help you!

**Comment by mattsage** [comment]
Yeah sure, please see log attached.
Thanks for your hard work!
Build version: 2.14.9 
Build date: 2016-06-07 19:22:26 
Current date: 2016-06-09 16:31:35 
Device: LGE Nexus 5 
Stack trace:  
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    ... 7 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    ... 15 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:619)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionSize(SessionProtobufHelper.java:554)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppSize(SessionProtobufHelper.java:510)
    at com.crashlytics.android.core.SessionProtobufHelper.getSessionEventSize(SessionProtobufHelper.java:482)
    at com.crashlytics.android.core.SessionProtobufHelper.writeSessionEvent(SessionProtobufHelper.java:180)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1052)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
    at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
    at android.support.design.widget.Snackbar.make(Snackbar.java:240)
    at com.alorma.github.ui.fragment.repos.ReposFragment.onResponseEmpty(ReposFragment.java:116)
    at com.alorma.github.presenter.repos.RepositoriesPresenter.action(RepositoriesPresenter.java:71)
    at com.alorma.github.presenter.repos.RepositoriesPresenter.lambda$execute$78(RepositoriesPresenter.java:59)
    at com.alorma.github.presenter.repos.RepositoriesPresenter.access$lambda$1(RepositoriesPresenter.java)
    at com.alorma.github.presenter.repos.RepositoriesPresenter$$Lambda$4.call(Unknown Source)
    at rx.Observable$28.onNext(Observable.java:8619)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
    at android.support.design.widget.Snackbar.make(Snackbar.java:240)
    at com.alorma.github.ui.fragment.repos.ReposFragment.onResponseEmpty(ReposFragment.java:116)
    at com.alorma.github.presenter.repos.RepositoriesPresenter.lambda$execute$79(RepositoriesPresenter.java:60)
    at com.alorma.github.presenter.repos.RepositoriesPresenter.access$lambda$2(RepositoriesPresenter.java)
    at com.alorma.github.presenter.repos.RepositoriesPresenter$$Lambda$5.call(Unknown Source)
    at rx.Observable$28.onError(Observable.java:8614)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
    ... 11 more

On 9 Jun 2016 16:19, Bernat Borrás Paronella notifications@github.com wrote:mmmmm ok, that's not cool.

Can you send me the log via mail? gitskarios@gmail.com, i will help you!

**Comment by alorma** [comment]
Fixed on 2.14.10 available in few hours

**Comment by mattsage** [comment]
Wow thank you so much! Really appreciate it!
On 9 Jun 2016 17:58, Bernat Borrás Paronella notifications@github.com wrote:Fixed on 2.14.10 available in few hours
