### ISSUE TITLE
crash on class open

### ISSUE THREAD

**Issue by Dafnik** [gitskarios/Gitskarios#461]
Build version: 2.14.11 
Build date: 2016-06-14 19:31:46 
Current date: 2016-06-15 10:24:56 
Device: HTC One 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.FileActivity}: java.lang.IllegalArgumentException: bad base-64
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.IllegalArgumentException: bad base-64
    at android.util.Base64.decode(Base64.java:161)
    at android.util.Base64.decode(Base64.java:136)
    at android.util.Base64.decode(Base64.java:118)
    at com.alorma.github.ui.fragment.FileFragment.decodeContent(FileFragment.java:224)
    at com.alorma.github.ui.fragment.FileFragment.onViewCreated(FileFragment.java:117)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
    at com.alorma.github.ui.activity.base.BackActivity.onStart(BackActivity.java:9)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
    at android.app.Activity.performStart(Activity.java:6006)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
    ... 10 more

**Comment by alorma** [comment]
Please, provide me a link example so i can reproduce

**Comment by alorma** [comment]
Should be fixed in v.2.14.12
