### ISSUE TITLE
Error while loading profile page

### ISSUE THREAD

**Issue by Unpublished** [gitskarios/Gitskarios#470]
Probably because of an empty avatar?

Build version: 2.15.2 
Build date: 2016-06-18 16:45:52 
Current date: 2016-06-21 15:44:31 
Device: Htc HTC One_M8 dual sim 

Stack trace:  
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
    at com.alorma.github.ui.activity.ProfileActivity.createLauncherIntent(ProfileActivity.java:94)
    at com.alorma.github.ui.view.UserAvatarView.onClick(UserAvatarView.java:84)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21158)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by GeorgeWL** [comment]
nah,  avatar has no effect on it, I had an empty avatar for ages.

Try cleaning up the format of your comment for us, so it's easier for us to figure out what the code says?

**Comment by alorma** [comment]
I don't know why, but in last times, some fields (user) are retrieved as null

I have to investigate why
