### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pkramme** [gitskarios/Gitskarios#479]
Build version: 2.16.0 
Build date: 2016-07-05 12:28:38 
Current date: 2016-07-05 12:25:24 
Device: Samsung SM-G900F 

Stack trace:  
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5832)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    ... 8 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    ... 15 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:619)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionSize(SessionProtobufHelper.java:554)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppSize(SessionProtobufHelper.java:510)
    at com.crashlytics.android.core.SessionProtobufHelper.getSessionEventSize(SessionProtobufHelper.java:482)
    at com.crashlytics.android.core.SessionProtobufHelper.writeSessionEvent(SessionProtobufHelper.java:180)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1032)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
    at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
    at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
    at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
    at com.alorma.github.ui.fragment.base.BaseFragment.isDarkTheme(BaseFragment.java:83)
    at com.alorma.github.ui.fragment.base.BaseFragment.getTheme(BaseFragment.java:68)
    at com.alorma.github.ui.fragment.base.BaseFragment.getContext(BaseFragment.java:49)
    at com.alorma.github.ui.fragment.base.LoadingListFragment.setEmpty(LoadingListFragment.java:205)
    at com.alorma.github.ui.fragment.commit.CommitStatusFragment$StatusCallback.onNext(CommitStatusFragment.java:134)
    at com.alorma.github.ui.fragment.commit.CommitStatusFragment$StatusCallback.onNext(CommitStatusFragment.java:103)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5832)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
    at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:374)
    at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:369)
    at com.alorma.github.ui.fragment.base.BaseFragment.isDarkTheme(BaseFragment.java:83)
    at com.alorma.github.ui.fragment.base.BaseFragment.getTheme(BaseFragment.java:68)
    at com.alorma.github.ui.fragment.base.BaseFragment.getContext(BaseFragment.java:49)
    at com.alorma.github.ui.fragment.base.LoadingListFragment.setEmpty(LoadingListFragment.java:205)
    at com.alorma.github.ui.fragment.commit.CommitStatusFragment$StatusCallback.onError(CommitStatusFragment.java:117)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
    ... 11 more

**Comment by alorma** [comment]
Fixed

**Comment by pkramme** [comment]
Watch out! We have a Quicksilver over here!

No joke, you are really fast with this. Thank you.
