### ISSUE TITLE
Crash on FileActivity

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#496]
Build version: 2.16.2 
Build date: 2016-07-09 01:18:54 
Current date: 2016-07-09 11:36:38 
Device: OnePlus ONEPLUS A3003 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.FileActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.dto.response.Content.content' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2456)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
    at android.app.ActivityThread.access$900(ActivityThread.java:159)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5507)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.dto.response.Content.content' on a null object reference
    at com.alorma.github.ui.fragment.FileFragment.onViewCreated(FileFragment.java:137)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1123)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
    at com.alorma.github.ui.activity.base.BackActivity.onStart(BackActivity.java:9)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1277)
    at android.app.Activity.performStart(Activity.java:6321)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
    ... 9 more

Its on every Commit File Preview

**Comment by alorma** [comment]
Yes, reproduced

Going to fix it now
