### ISSUE TITLE
crash when switching to code tab of a repository

### ISSUE THREAD

**Issue by griest024** [gitskarios/Gitskarios#507]
When I am viewing a repo, switching to the code tab, swipe or tap, causes the app to crash.

Build version: 2.17.1 
Build date: 2016-07-16 18:00:56 
Current date: 2016-07-17 12:15:08 
Device: Samsung SCH-I545 

Stack trace:  
java.lang.NoSuchMethodError: android.graphics.drawable.Drawable.setTint
    at com.alorma.github.ui.fragment.detail.repo.SourceListFragment.onPrepareOptionsMenu(SourceListFragment.java:243)
    at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2187)
    at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:2270)
    at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:340)
    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:537)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
    at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
    at android.view.Choreographer.doCallbacks(Choreographer.java:603)
    at android.view.Choreographer.doFrame(Choreographer.java:572)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5356)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method) ```

```
```

**Comment by alorma** [comment]
Fixed

**Comment by griest024** [comment]
That was fast

**Comment by alorma** [comment]
:) I was fixing issues :P

Test is once it's updated from play store

**Comment by griest024** [comment]
Yup its fixed
