### ISSUE TITLE
Update Broke Everything!

### ISSUE THREAD

**Issue by mariobrostech** [gitskarios/Gitskarios#520]
Log below:
Build version: 2.17.3 
Build date: 2016-07-17 18:07:20 
Current date: 2016-07-28 12:01:59 
Device: Samsung SM-G930P 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.alorma.github.sdk.core.User.getLogin()' on a null object reference
    at com.alorma.github.ui.fragment.repos.ReposAdapter.onBindViewHolder(ReposAdapter.java:48)
    at com.alorma.github.ui.fragment.repos.ReposAdapter.onBindViewHolder(ReposAdapter.java:21)
    at com.alorma.github.ui.adapter.base.RecyclerArrayAdapter.onBindViewHolder(RecyclerArrayAdapter.java:53)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:598)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1759)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
    at android.view.View.layout(View.java:17945)
    at android.view.ViewGroup.layout(ViewGroup.java:5812)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7467)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    at android.view.Choreographer.doCallbacks(Choreographer.java:695)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by droped** [comment]
Delete the app's data and cache and open the app again.

**Comment by mariobrostech** [comment]
Did that, I stayed signed in for some reason! Still doesn't work!!! Same errors.

**Comment by droped** [comment]
IIRC the app creates accounts using android's account manager so deleting the app's data would not delete your login info. Try delete your account from the system settings and deleting the app's data and cache again and then openning the app again.

**Comment by mariobrostech** [comment]
Still didn't work, please help!
Device info:
Samsung Galaxy S7
Android 6.0.1 Marshmallow

**Comment by droped** [comment]
I don't know honestly. Mine works fine (lg g3/ cm13). Must be a stock samsung rom problem.

**Comment by alorma** [comment]
I will check tomorrow, sorry for crashes

**Comment by mariobrostech** [comment]
It's fine, just please try to fix this ASAP. I have a website to manage!
