### ISSUE TITLE
Crash on Edit file, while the file is loading

### ISSUE THREAD

**Issue by shyim** [gitskarios/Gitskarios#521]
Build version: 2.17.10 
Build date: 2016-07-30 13:02:46 
Current date: 2016-07-30 18:36:45 
Device: OnePlus ONEPLUS A3003 

Stack trace:  
java.lang.RuntimeException: Failure from system
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1615)
    at android.app.Activity.startActivityForResult(Activity.java:3982)
    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
    at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:31)
    at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:163)
    at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:948)
    at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1057)
    at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:947)
    at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:936)
    at com.alorma.github.ui.fragment.FileFragment.editContent(FileFragment.java:186)
    at com.alorma.github.ui.fragment.FileFragment.onOptionsItemSelected(FileFragment.java:179)
    at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2199)
    at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2284)
    at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:427)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:188)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
    at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:947)
    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
    at android.view.View.performClick(View.java:5233)
    at android.view.View$PerformClick.run(View.java:21209)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5507)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.os.TransactionTooLargeException: data parcel size 1805232 bytes
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:527)
    at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2805)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:160

8)
    ... 36 more

**Comment by GeorgeWL** [comment]
thanks for the detailed log @shyim , can you give us a few extra details too:

What exactly are the steps you take that cause the problem?

Is it repeatable when you take the same steps?

Just so that we can pinpoint exactly what would cause it more easily, cause the stack log is often overly verbose, making it not as helpful as it should be.

**Comment by shyim** [comment]
Open big file while the content is loading press on top right the edit button. It will crash everytime

**Comment by alorma** [comment]
Provide a big file linke plz

**Comment by shyim** [comment]
https://github.com/shyim/shopware/blob/5.0/_sql/install/latest.sql
