### ISSUE TITLE
Unexpected bug while unwatching my repository

### ISSUE THREAD

**Issue by RememberTheAir** [gitskarios/Gitskarios#535]
Build version: 3.1.1 
Build date: 2016-08-13 21:42:40 
Current date: 2016-08-14 12:44:32 
Device: OnePlus A0001 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
    at com.alorma.github.ui.fragment.detail.repo.RepoAboutFragment.changeWatchedStatus(RepoAboutFragment.java:459)
    at com.alorma.github.ui.fragment.detail.repo.RepoAboutFragment.lambda$onViewCreated$3(RepoAboutFragment.java:199)
    at com.alorma.github.ui.fragment.detail.repo.RepoAboutFragment.access$lambda$3(RepoAboutFragment.java)
    at com.alorma.github.ui.fragment.detail.repo.RepoAboutFragment$$Lambda$4.onEvent(Unknown Source)
    at com.varunest.sparkbutton.SparkButton.onClick(SparkButton.java:215)
    at android.view.View.performClick(View.java:5204)
    at com.varunest.sparkbutton.SparkButton$2.onTouch(SparkButton.java:243)
    at android.view.View.dispatchTouchEvent(View.java:9297)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2665)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1793)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3076)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:63)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2626)
    at android.view.View.dispatchPointerEvent(View.java:9521)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:323)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by RememberTheAir** [comment]
Ups, I thought I was sending a classic email to the developer instead to open an issue :)

This may look a bit spammish... fell free to close it

**Comment by alorma** [comment]
Fixed

**Comment by RememberTheAir** [comment]
Great, thanks a lot :)
