### ISSUE TITLE
In about section, the CardView aren't associate with dark theme.

### ISSUE THREAD

**Issue by ghost** [gitskarios/Gitskarios#541]

**Comment by alorma** [comment]
Please, provider more info, and screenshots

**Comment by ghost** [comment]
Lol, I tried to send you a picture of the bug with your app, but it will not let me, and then opens the appropriate screen for more information of the error.

Error message : 

Build version: 3.1.1 
Build date: 2016-08-13 21:42:40 
Current date: 2016-08-18 15:27:44 
Device: HUAWEI VNS-L31 

Stack trace:  
java.lang.IllegalStateException: Only one Dexter request at a time is allowed
    at com.karumi.dexter.DexterInstance.checkNoDexterRequestOngoing(DexterInstance.java:271)
    at com.karumi.dexter.DexterInstance.checkMultiplePermissions(DexterInstance.java:290)
    at com.karumi.dexter.DexterInstance.checkSinglePermission(DexterInstance.java:285)
    at com.karumi.dexter.DexterInstance.checkPermission(DexterInstance.java:77)
    at com.karumi.dexter.Dexter.checkPermission(Dexter.java:74)
    at com.alorma.github.ui.activity.ContentEditorActivity.showImageUploadPicker(ContentEditorActivity.java:344)
    at com.alorma.github.ui.activity.ContentEditorActivity.lambda$showAddPicture$1(ContentEditorActivity.java:315)
    at com.alorma.github.ui.activity.ContentEditorActivity.access$lambda$1(ContentEditorActivity.java)
    at com.alorma.github.ui.activity.ContentEditorActivity$$Lambda$2.onClick(Unknown Source)
    at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:364)
    at android.view.View.performClick(View.java:5273)
    at android.view.View$PerformClick.run(View.java:21315)
    at android.os.Handler.handleCallback(Handler.java:743)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:5639)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

**Comment by GeorgeWL** [comment]
Can you tell us a bit of details?

like is it always happening or only under certain circumstances?
