### ISSUE TITLE
Crash when rotating during pull request page load 

### ISSUE THREAD

**Issue by MelvynEzi** [gitskarios/Gitskarios#557]
Build version: 4.4.1 
Build date: 2016-09-04 10:27:50 
Current date: 2016-09-05 18:47:36 
Device: LGE LG-D838 

Stack trace:  
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5290)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:186)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    ... 8 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    ... 14 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:619)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionSize(SessionProtobufHelper.java:554)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppSize(SessionProtobufHelper.java:510)
    at com.crashlytics.android.core.SessionProtobufHelper.getSessionEventSize(SessionProtobufHelper.java:482)
    at com.crashlytics.android.core.SessionProtobufHelper.writeSessionEvent(SessionProtobufHelper.java:180)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1032)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
    at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object com.alorma.github.sdk.bean.issue.Story.item' on a null object reference
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment.notifyHeadOfAdapter(PullRequestConversationFragment.java:339)
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment.access$600(PullRequestConversationFragment.java:63)
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment$3.onNext(PullRequestConversationFragment.java:332)
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment$3.onNext(PullRequestConversationFragment.java:320)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5290)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object com.alorma.github.sdk.bean.issue.Story.item' on a null object reference
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment.notifyHeadOfAdapter(PullRequestConversationFragment.java:339)
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment.access$600(PullRequestConversationFragment.java:63)
    at com.alorma.github.ui.fragment.pullrequest.PullRequestConversationFragment$3.onError(PullRequestConversationFragment.java:327)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    ... 10 more

**Comment by LetItRock** [comment]
This should be fixed after merging pull request: #559

**Comment by LetItRock** [comment]
Please check if this is still reproducible with next release...

**Comment by MelvynEzi** [comment]
Seems good
