### ISSUE TITLE
Can't Open Mentioned Issues Section!

### ISSUE THREAD

**Issue by mariobrostech** [gitskarios/Gitskarios#567]
Device info:
Samsung Galaxy S7
Android 6.0.1 Marshmallow

Error code:
Build version: 4.4.2 
Build date: 2016-09-10 18:14:58 
Current date: 2016-09-11 09:06:14 
Device: Samsung SM-G930P 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'com.alorma.github.sdk.core.User com.alorma.github.sdk.core.repositories.Repo.getOwner()' on a null object reference
    at com.alorma.github.ui.fragment.issues.user.UserIssuesListFragment.onItemSelected(UserIssuesListFragment.java:123)
    at com.alorma.github.ui.fragment.issues.user.UserIssuesListFragment.onItemSelected(UserIssuesListFragment.java:30)
    at com.alorma.github.ui.fragment.issues.user.IssuesAdapter$ViewHolder.lambda$new$0(IssuesAdapter.java:128)
    at com.alorma.github.ui.fragment.issues.user.IssuesAdapter$ViewHolder.access$lambda$0(IssuesAdapter.java)
    at com.alorma.github.ui.fragment.issues.user.IssuesAdapter$ViewHolder$$Lambda$1.onClick(Unknown Source)
    at android.view.View.performClick(View.java:5702)
    at android.view.View$PerformClick.run(View.java:22533)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by alorma** [comment]
I'm aware of the bug, i will fix it asab

**Comment by alorma** [comment]
Fixed :D
