### ISSUE TITLE
Crash when attempting to view code on md files

### ISSUE THREAD

**Issue by MelvynEzi** [gitskarios/Gitskarios#573]
Build version: 4.4.3 <br />Build date: 2016-09-11 20:49:48 <br />Current date: 2016-09-13 18:42:40 <br />Device: LGE LG-D838 <br /><br />Stack trace:  <br />java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.info.RepoInfo.branch' on a null object reference<br /> at com.alorma.github.sdk.services.content.GetFileContentClient.getApiObservable(GetFileContentClient.java:21)<br /> at com.alorma.gitskarios.core.client.BaseClient.observable(BaseClient.java:45)<br />    at com.alorma.github.ui.fragment.content.source.FileFragment.getContentObservable(FileFragment.java:22)<br />   at com.alorma.github.ui.fragment.content.BaseFileFragment.getContent(BaseFileFragment.java:43)<br />    at com.alorma.github.ui.fragment.content.BaseFileFragment.onStart(BaseFileFragment.java:38)<br />   at android.support.v4.app.Fragment.performStart(Fragment.java:2106)<br />   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)<br />  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)<br />  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)<br />   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)<br />   at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)<br /> at android.os.Handler.handleCallback(Handler.java:739)<br />    at android.os.Handler.dispatchMessage(Handler.java:95)<br />    at android.os.Looper.loop(Looper.java:135)<br />    at android.app.ActivityThread.main(ActivityThread.java:5290)<br />  at java.lang.reflect.Method.invoke(Native Method)<br /> at java.lang.reflect.Method.invoke(Method.java:372)<br />   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)<br />    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)<br />

**Comment by alorma** [comment]
Hi, I protected it from crash.

Please, could you provide a way to reproduce? Link?

**Comment by MelvynEzi** [comment]
Could be due to internet connection. Will check again.

**Comment by MelvynEzi** [comment]
EDIT: Found out that it crashes when attempting to view from a Pull Request.

In addition, render shows the following.

![Screenshot_2016-09-15-10-06-29.png](http://i.imgur.com/lcYsnHj.png)
