### ISSUE TITLE
Crash when trying to view image in Pull Requests

### ISSUE THREAD

**Issue by MelvynEzi** [gitskarios/Gitskarios#578]
Build version: 4.4.3 
Build date: 2016-09-11 20:49:48 
Current date: 2016-09-15 09:56:06 
Device: LGE LG-D838 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.FileActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.info.RepoInfo.branch' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2366)
    at android.app.ActivityThread.access$800(ActivityThread.java:149)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5290)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.info.RepoInfo.branch' on a null object reference
    at com.alorma.github.sdk.services.content.GetFileContentClient.getApiObservable(GetFileContentClient.java:21)
    at com.alorma.gitskarios.core.client.BaseClient.observable(BaseClient.java:45)
    at com.alorma.github.ui.fragment.content.source.ImageFileFragment.getContentObservable(ImageFileFragment.java:20)
    at com.alorma.github.ui.fragment.content.BaseFileFragment.getContent(BaseFileFragment.java:43)
    at com.alorma.github.ui.fragment.content.BaseFileFragment.onStart(BaseFileFragment.java:38)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2106)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
    at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2154)
    at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
    at com.alorma.github.ui.activity.base.BackActivity.onStart(BackActivity.java:9)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
    at android.app.Activity.performStart(Activity.java:6036)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
    ... 10 more

**Comment by LetItRock** [comment]
This crash also happenes when trying to check image file from commit info window. I will investigate that.
