### ISSUE TITLE
Broken diff view and crash when viewing a file in a PR

### ISSUE THREAD

**Issue by nisavid** [gitskarios/Gitskarios#579]
When I view a PR, then navigate to its files, then tap on a file, I see two oddities:
- The diff contents are shown entirely on one very long line.  The previous view (with multiple files) looks fine, but the single-file view is messed up.

![Broken single-file diff view](https://drive.google.com/uc?export=view&id=124_uLL0s-82tQ3QR26rKJvihA2sUYm9sHw)
- If I tap _CODE_, Gitskarios brings me to an error page that says "An unexpected error occurred" and offers to _RESTART APP_ or show _ERROR DETAILS_.  The details show the following backtrace:

```
Build version: 4.4.3 
Build date: 2016-09-11 20:49:48 
Current date: 2016-09-14 23:12:45 
Device: Huawei Nexus 6P 

Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.alorma.github.sdk.bean.info.RepoInfo.branch' on a null object reference
    at com.alorma.github.sdk.services.content.GetFileContentClient.getApiObservable(GetFileContentClient.java:21)
    at com.alorma.gitskarios.core.client.BaseClient.observable(BaseClient.java:45)
    at com.alorma.github.ui.fragment.content.source.FileFragment.getContentObservable(FileFragment.java:22)
    at com.alorma.github.ui.fragment.content.BaseFileFragment.getContent(BaseFileFragment.java:43)
    at com.alorma.github.ui.fragment.content.BaseFileFragment.onStart(BaseFileFragment.java:38)
    at android.support.v4.app.Fragment.performStart(Fragment.java:2106)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1146)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This is with Gitskarios 2.15.0 on a Nexus 6P running Android 7.0.

I think this worked for me recently, so I wonder if it's related to GitHub's [latest changes](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features).

**Comment by MelvynEzi** [comment]
Same as reported in #573

**Comment by MelvynEzi** [comment]
Damn this is annoying me a lot.. find myself using the mobile site more. :(

**Comment by alorma** [comment]
Will fix today, sorry
