### ISSUE TITLE
Crash when tapping on a Milestone

### ISSUE THREAD

**Issue by fahrradflucht** [gitskarios/Gitskarios#587]
Steps to reproduce 
- Go to the issues of a repo
- Hit the milestone icon in the upper right corner
- tap on a milestone

Crash message:

```
Build version: 4.4.4 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-05 08:56:57 
Device: Sony D5503 

Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66748, result=-1, data=Intent { (has extras) }} to activity {com.alorma.github/com.alorma.github.ui.activity.repo.RepoDetailActivity}: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.Milestone
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3680)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3723)
    at android.app.ActivityThread.access$1300(ActivityThread.java:156)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.Milestone
    at com.alorma.github.ui.fragment.issues.RepositoryIssuesListFragment.onActivityResult(RepositoryIssuesListFragment.java:326)
    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
    at com.alorma.github.ui.activity.repo.RepoDetailActivity.onActivityResult(RepoDetailActivity.java:420)
    at android.app.Activity.dispatchActivityResult(Activity.java:6192)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3676)
    ... 10 more 

```

**Comment by webmaster33** [comment]
I also get crash, when changing milestone: 
Build version: 4.4.8 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-31 17:13:35 
Device: Samsung GT-I9305 

Stack trace:  
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66748, result=-1, data=Intent { (has extras) }} to activity {com.alorma.github/com.alorma.github.ui.activity.repo.RepoDetailActivity}: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.Milestone
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3182)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3225)
    at android.app.ActivityThread.access$1100(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1275)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4898)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: com.alorma.github.sdk.bean.dto.response.ShaUrl cannot be cast to com.alorma.github.sdk.bean.dto.response.Milestone
    at com.alorma.github.ui.fragment.issues.RepositoryIssuesListFragment.onActivityResult(RepositoryIssuesListFragment.java:326)
    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
    at com.alorma.github.ui.activity.repo.RepoDetailActivity.onActivityResult(RepoDetailActivity.java:448)
    at android.app.Activity.dispatchActivityResult(Activity.java:5368)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3178)
    ... 11 more

**Comment by webmaster33** [comment]
This seems to work in last version.
