### ISSUE TITLE
Event page error

### ISSUE THREAD

**Issue by sc4ryb3ar** [gitskarios/Gitskarios#603]
Got this today when I was trying to view a comment in my Events page. I believe it has been deleted...dunno though, not in a place I can check.

Build version: 4.4.8 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-21 11:28:52 
Device: LGE D850 

Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String core.User.getLogin()' on a null object reference
    at core.repositories.Repo.toInfo(Repo.java:333)
    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:380)
    at com.alorma.github.ui.fragment.events.EventsListFragment.onItemSelected(EventsListFragment.java:60)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.lambda$populate$0(EventViewHolder.java:39)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder.access$lambda$0(EventViewHolder.java)
    at com.alorma.github.ui.adapter.events.holders.EventViewHolder$$Lambda$1.onClick(Unknown Source)
    at android.view.View.performClick(View.java:5609)
    at android.view.View$PerformClick.run(View.java:22266)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6137)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by alorma** [comment]
Done
