### ISSUE TITLE
Crashes All the time

### ISSUE THREAD

**Issue by tomscholz** [gitskarios/Gitskarios#607]
Build version: 4.4.8 
Build date: 1979-11-30 00:00:00 
Current date: 2016-10-23 18:17:59 
Device: OnePlus ONEPLUS A3003 

Stack trace:  
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5507)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:186)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:86)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    ... 8 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    ... 17 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:619)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionExceptionSize(SessionProtobufHelper.java:622)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppExecutionSize(SessionProtobufHelper.java:554)
    at com.crashlytics.android.core.SessionProtobufHelper.getEventAppSize(SessionProtobufHelper.java:510)
    at com.crashlytics.android.core.SessionProtobufHelper.getSessionEventSize(SessionProtobufHelper.java:482)
    at com.crashlytics.android.core.SessionProtobufHelper.writeSessionEvent(SessionProtobufHelper.java:180)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1032)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
    at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
    at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.alorma.github.presenter.View.onDataReceived(java.lang.Object, boolean)' on a null object reference
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter.lambda$execute$4(IssueMilestonePresenter.java:43)
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter.access$lambda$3(IssueMilestonePresenter.java)
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter$$Lambda$4.call(Unknown Source)
    at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
    at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:86)
    at rx.observers.Subscribers$5.onNext(Subscribers.java:235)
    at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
    at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:152)
    at android.app.ActivityThread.main(ActivityThread.java:5507)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.alorma.github.presenter.View.showError(java.lang.Throwable)' on a null object reference
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter.lambda$execute$5(IssueMilestonePresenter.java:44)
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter.access$lambda$4(IssueMilestonePresenter.java)
    at com.alorma.github.ui.activity.issue.IssueMilestonePresenter$$Lambda$5.call(Unknown Source)
    at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    ... 13 more

**Comment by webmaster33** [comment]
It seems, Xposed is installed.

**Comment by tomscholz** [comment]
@webmaster33 Is that a problem? :)

**Comment by webmaster33** [comment]
Xposed can cause problems sometimes. Not necessarily Xposed is the problem, but it can be.

**Comment by alorma** [comment]
I most not do support to rooted devices, i will check this crash trying to fix it

**Comment by alorma** [comment]
Done
