### ISSUE TITLE
Crash while trying  to open a repository 

### ISSUE THREAD

**Issue by Wolfteam** [gitskarios/Gitskarios#642]
Build version: v.4.7.3 
Build date: 1979-11-30 00:00:00 
Current date: 2016-11-23 21:44:05 
Device: Asus Nexus 7 

Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alorma.github/com.alorma.github.ui.activity.repo.RepoDetailActivity}: android.view.InflateException: Binary XML file line #38: Error inflating class Button
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #38: Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.alorma.github.ui.activity.repo.RepoAboutFragment.onCreateView(RepoAboutFragment.java:128)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
	at com.alorma.github.ui.activity.base.BackActivity.onStart(BackActivity.java:9)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
	at android.app.Activity.performStart(Activity.java:5241)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
	... 11 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_star_vector.xml from drawable resource ID #0x7f0200b8
	at android.content.res.Resources.loadDrawable(Resources.java:2235)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.TextView.<init>(TextView.java:806)
	at android.widget.Button.<init>(Button.java:107)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:64)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:60)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1076)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 29 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2231)
	... 40 more

**Comment by alorma** [comment]
Repository link plz?

**Comment by Wolfteam** [comment]
This for exameple :https://github.com/Wolfteam/app
i think all the repos that i have crashes the app, btw im using a nexus 7

**Comment by shyim** [comment]
Is the problem still reproducible on your tablet? I tried and cannot find a problem.

**Comment by Wolfteam** [comment]
nop, the issue was fixed :+1:

**Comment by shyim** [comment]
Okay :)
