### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by webmaster33** [gitskarios/Gitskarios#652]
Using Samsung Galaxy S4 i9505 jfltexx with stock Android 5.0.1.
Crash happened when changing within repository from Issues tab to Home tab. 

Build version: v.4.8.0 
Build date: 1979-11-30 00:00:00 
Current date: 2017-01-06 13:51:17 
Device: Samsung GT-I9505 

Stack trace:  
android.view.InflateException: Binary XML file line #74: Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at com.alorma.github.ui.activity.repo.RepoAboutFragment.onCreateView(RepoAboutFragment.java:128)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_repo_tag.xml from drawable resource ID #0x7f0200a5
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.widget.TextView.<init>(TextView.java:1226)
	at android.widget.Button.<init>(Button.java:115)
	at android.widget.Button.<init>(Button.java:108)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:64)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:60)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1076)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:181)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_tag.xml from drawable resource ID #0x7f0200ad
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:238)
	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:195)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 34 more
Caused by: java.lang.NumberFormatException: Invalid float: ".66.27"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:160)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 42 more

**Comment by webmaster33** [comment]
Reproduced:
Build version: v.4.8.0 
Build date: 1979-11-30 00:00:00 
Current date: 2017-01-06 14:05:07 
Device: Samsung GT-I9505 

Stack trace:  
android.view.InflateException: Binary XML file line #74: Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at com.alorma.github.ui.activity.repo.RepoAboutFragment.onCreateView(RepoAboutFragment.java:128)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_repo_tag.xml from drawable resource ID #0x7f0200a5
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.widget.TextView.<init>(TextView.java:1226)
	at android.widget.Button.<init>(Button.java:115)
	at android.widget.Button.<init>(Button.java:108)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:64)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:60)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1076)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:181)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_tag.xml from drawable resource ID #0x7f0200ad
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:238)
	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:195)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 34 more
Caused by: java.lang.NumberFormatException: Invalid float: ".66.27"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:160)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 42 more

**Comment by webmaster33** [comment]
Strange. The crash happens only on my Samsung Galaxy S4 i9505 with stock Android v5.0.1 when I switch from Issues tab to Home tab. 
On Samsung Galaxy S3 i9305 with MIUI v5 (Android v4.1.1) switching to Home tab works fine. 

So this may be a compatibility problem with Android Lollipop and higher.

**Comment by webmaster33** [comment]
Still having crash, when changing to home of a repo:
 ```
Build version: v.4.8.0 
Build date: 1979-11-30 00:00:00 
Current date: 2017-01-20 08:50:54 
Device: Samsung GT-I9505 

Stack trace:  
android.view.InflateException: Binary XML file line #74: Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at com.alorma.github.ui.activity.repo.RepoAboutFragment.onCreateView(RepoAboutFragment.java:128)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_repo_tag.xml from drawable resource ID #0x7f0200a5
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.widget.TextView.<init>(TextView.java:1226)
	at android.widget.Button.<init>(Button.java:115)
	at android.widget.Button.<init>(Button.java:108)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:64)
	at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:60)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1076)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:181)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
	... 21 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_tag.xml from drawable resource ID #0x7f0200ad
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3735)
	at android.content.res.Resources.loadDrawable(Resources.java:3603)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:238)
	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:195)
	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 34 more
Caused by: java.lang.NumberFormatException: Invalid float: ".66.27"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:160)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1150)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1063)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:3719)
	... 42 more

 ```

**Comment by webmaster33** [comment]
Somebody could fix this crash for a small donation?

**Comment by alorma** [comment]
Hi @webmaster33.

This is not a "pay" project.

Could you try to fix it?

**Comment by webmaster33** [comment]
Unfortunately I don't know Java. However I plan to learn it :-)
